### ISSUE TITLE
Bash: $ signs are not escaped

### ISSUE THREAD

**Issue by nablaoperator** [nearform/node-clinic#122]
Stand-alone Autocannon works ($'s are correctly escaped)
`autocannon "http://localhost:8080/Catalog/Orders?\$top=15&\$expand=book" -c 100 -d 10`
`Running 10s test @ http://localhost:8080/Catalog/Orders?$top=15&$expand=book`

## Expected Behavior
Autocannon inside node clinic should work, too:

`clinic flame --autocannon [ "http://localhost:8080/Catalog/Orders?\$top=15&\$expand=book" -c 100 -d 10 ] -- node srv/server.js `
`Server listens on port 8080 - Service URL: http://localhost:8080/
Running 10s test @ http://localhost:8080/Catalog/Orders?$top=15&$expand=book`

## Current Behavior
However, it actually behaves like this:
`clinic flame --autocannon [ "http://localhost:8080/Catalog/Orders?\$top=15&\$expand=book" -c 100 -d 10 ] -- node srv/server.js `
`Server listens on port 8080 - Service URL: http://localhost:8080/
Running 10s test @ http://localhost:8080/Catalog/Orders?=15&=book`

So the $'s are not escaped

## Steps to Reproduce (for bugs)
Just execute the given commands.

## Environment
* Clinic version: v2.2.1
Ubuntu Linux 16.04
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

* Node version: v8.11.4

**Comment by goto-bus-stop** [comment]
With `clinic --autocannon`, clinic starts the autocannon subprocess, and environment variables are also resolved at that time. We inline environment variables to support this case:

```js
clinic flame --autocannon [ 'http://localhost:$PORT/path/to/endpoint' -d 1 ] -- node server.js
```

Here, `$PORT` will be replaced by the port that `node server.js` is listening on.
We could:
 - only inline `$PORT`, and not any other environment variables, which may be surprising, or;
 - test and document that escaping `'\$top'` and `"\\\$top"` works, which is annoying

**Comment by DaveKu** [comment]
Thanks for your answer. 
I would prefer the second option since it's, as you say, less surprising and also covers more cases.
Thanks a lot!

**Comment by DylanC** [comment]
@goto-bus-stop - Anything to action for this one?

**Comment by goto-bus-stop** [comment]
@DylanC Looks like this was addressed. Thanks for checking in!
