### ISSUE TITLE
Confusing CPU Usage display

### ISSUE THREAD

**Issue by gboysko** [nearform/node-clinic#13]
I was able to finish a 10 minute analysis of my Node.js application which uses `socket.io` and a MongoDB backend. When I looked at the results (I uploaded them to ID: 6f8316c279ccbc2c587e33a2a3731b2f2aefe79d7d065ed542ef7241fd61bad3), I found (rightly so) that I may have a potential I/O issue. 

Here are my questions about the chart:

1. The CPU Usage chart has a vertical axis that ranges from 0 to 200. Given that I have a single process, I'm not sure how we could be using over 100% of the CPU. 
1. Does the CPU Usage chart also overlay some I/O statistics? It seems like there are two bar charts: one with red bars and one with green bars (though the green ones are very, very short).
1. When I hover over data points, the tooltip display shows low values (generally < 10%), however the chart has tall red bars (some which go over 200) that don't reflect the tooltip. 

Overall, the UI is really helpful, though the hover responsiveness is lagging, slow. I understand that there is a lot of data in the page.

**Comment by mcollina** [comment]
Thanks for checking it out! I had a look at your diagram, and you might benefit in generating a flamegraph anyway. 

> The CPU Usage chart has a vertical axis that ranges from 0 to 200. Given that I have a single process, I'm not sure how we could be using over 100% of the CPU.

Node.js runs multiple threads, and some of those are from V8 (our JS runtime). Both the Garbage Collector and the Optimizing Compiler are run on separate threads (most of the times), so if there is a spike of activity there you can easily have 200% CPU.
We should definitely explain this in the text.

> Does the CPU Usage chart also overlay some I/O statistics? It seems like there are two bar charts: one with red bars and one with green bars (though the green ones are very, very short).

There is no I/O there.

> When I hover over data points, the tooltip display shows low values (generally < 10%), however the chart has tall red bars (some which go over 200) that don't reflect the tooltip.

Can you please rephrase and/or make a screenshot? I don't understand.

**Comment by gboysko** [comment]
It definitely seems odd that multiple threads would cause the CPU stats collection to increase overall process usage over 100%. What NPM module are using to capture CPU usage? Are you collecting stats for the process? Or summing up CPU usage on a per-thread basis?

I'm including two screen shots. The first shows a portion of the CPU usage chart.

![clinicdoctor](https://user-images.githubusercontent.com/636721/37299573-13d5c3e4-25fa-11e8-8300-6d554404aa79.png)

The first thing you should notice is the high red bars for CPU. You might also notice that the tooltip menu is position *on top* instead of above the bar.

Here is a zoomed imaged as well.

![clientdoctorzoomed](https://user-images.githubusercontent.com/636721/37299643-43233546-25fa-11e8-81af-e21add40abaf.png)

In this image, you can see a second set of bars (perhaps green?) and the tooltip seems to be positioned above these bars. That's why I felt that we are displaying two different bar charts (overlayed on each other).

**Comment by mcollina** [comment]
> It definitely seems odd that multiple threads would cause the CPU stats collection to increase overall process usage over 100%. What NPM module are using to capture CPU usage? Are you collecting stats for the process? Or summing up CPU usage on a per-thread basis?

It's summing up the various threads, and as you have a multithread/multicore CPU it can go over 100%.
Here is the code that does that compute if you are curious: https://github.com/nearform/node-clinic-doctor/blob/master/collect/process-stat.js.

**Comment by mafintosh** [comment]
@gboysko what @matteo said :). also even though you only have a single core your CPU might have hyperthreads which appear like cores in the APIs usually. We use the node core `os` module to collect the information

**Comment by gboysko** [comment]
Thanks, guys. And it wouldn't make sense to normalize the CPU stats? So that if you sum up all of the CPU usage across all processes (the Node.js process under test as well as other OS process), the total would never be more than 100%?

Any thoughts on presence of two sets of bars?

**Comment by davidmarkclements** [comment]
@gboysko I think that's just a rendering artifact, there's one set of bars, the red ones.

**Comment by gboysko** [comment]
Thanks @davidmarkclements, however the tooltip doesn't seem to reflect what is shown in the bars. That is, the bars have values beyond 200%, yet the tooltip value shown is 10% or less. I can't see how this presentation is intuitive if it is by design.
