### ISSUE TITLE
Cant use node environment variables

### ISSUE THREAD

**Issue by Phara0h** [nearform/node-clinic#148]
## Expected Behavior
Should allow env to be set like it says you can in the documentation 
https://clinicjs.org/documentation/cli

## Current Behavior
```
clinic doctor -- NODE_PATH="." node index.js 
To generate the report press: Ctrl + C
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn NODE_PATH=. ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```

## Steps to Reproduce (for bugs)
1. try to run ```clinic doctor -- NODE_PATH="." node index.js ``` 

## Environment
* Clinic.js version: Clinic.js v4.0.2 Doctor v4.0.2
* Node.js version: v10.14.2
* Operating system and version: OSX 10.14.3

**Comment by goto-bus-stop** [comment]
hmm, i don't think this was ever actually supported!

you can do `NODE_ENV=production clinic doctor -- node server.js` in most (all?) cases, instead, since `server.js` will just inherit the env from `clinic`.

if there is a case where the `ENV=val clinic doctor -- node server.js` form doesn't work as intended, but `clinic doctor -- ENV=val node server.js` would, we could support that too.

thanks for opening an issue, i'll look into fixing the docs.

**Comment by Phara0h** [comment]
> hmm, i don't think this was ever actually supported!
> 
> you can do `NODE_ENV=production clinic doctor -- node server.js` in most (all?) cases, instead, since `server.js` will just inherit the env from `clinic`.
> 
> if there is a case where the `ENV=val clinic doctor -- node server.js` form doesn't work as intended, but `clinic doctor -- ENV=val node server.js` would, we could support that too.
> 
> thanks for opening an issue, i'll look into fixing the docs.

Thanks for the reply so this is our "npm start" script that gets ran.

```
export NODE_PATH="$(pwd)/src/lib"
export $(sed -e '/^#/d' .env | xargs)

node src/index.js
```

That second export is setting a bunch of environment variables in a text file and for some reason clinic wont work with it.

**Comment by samartioli** [comment]
Can work around by using a pre-launch script and including the .env implicitly with the `dotenv` npm module

```
'use strict';
var path = require('path');

require('dotenv').config({path: path.join(__dirname, '.env')});

process.env.NODE_PATH = path.join(__dirname, 'src/lib');

require('src/index.js');
```

**Comment by DylanC** [comment]
@goto-bus-stop - Seems a fix was pushed for this already?
