### ISSUE TITLE
'Ctrl+C' exit after can't generate traceevent file.

### ISSUE THREAD

**Issue by atlantismonk** [nearform/node-clinic#152]
## Expected Behavior
i happen have traceevent file in `.clinic` folder.

## Current Behavior
 `Ctrl+C` after `@nearform/doctor` can’t trigger 'SIGINT' event execute move trace_event file to logging directory and analysing.

## Steps to Reproduce (for bugs)
1. `node_modules/.bin/clinic doctor -- node bin/www`
2. typing `Ctrl+C`
3. and project root folder generated `node_trace.1.log`
4. and the program is over

## Environment
* Clinic.js version: v4.0.2
* clinic doctor version: v4.0.3
* Node.js version: v10.14.1
* npm version: 6.4.1
* Operating system and version: MacOS Mojave 10.14.4

## Supplement
use `kill -2` exit is ok.

**Comment by goto-bus-stop** [comment]
This was most likely fixed by https://github.com/nearform/node-clinic/pull/150, could you try with `clinic@4.0.3`?

**Comment by fr-nevin** [comment]
@atlantismonk https://github.com/nearform/node-clinic/issues/164
Am having the same issue. Was this fixed? 
It's working fine on Linux for my friends, but not on MAC.

**Comment by atlas1119** [comment]
I have the same issue,   Clinic - v4.1.0,   node 9.4.0 ,  on linux

**Comment by casperle** [comment]
Same here.
clinic v4.1.0
node v11.7.0

After control+c I got only this:
[    ] Received Ctrl+C, closing process...

The folder with processstat and systemunfo is generated but anything else.

**Comment by DylanC** [comment]
@atlantismonk - Can you try Clinic v5 and let us know if you still have an issue?

**Comment by DylanC** [comment]
Tested as working in #164.

**Comment by clcoco** [comment]
I have the same issue right now...
