### ISSUE TITLE
async hook stack has become corrupted

### ISSUE THREAD

**Issue by stephen-dunn** [nearform/node-clinic#161]
## Expected Behavior
I should expect to not see a stack trace when using `clinic bubbleprof`

## Current Behavior
Whenever I start `clinic bubbleprof` I always see:
```
Error: async hook stack has become corrupted (actual: 29, expected: 1)
process exited with exit code 1
Analysing data
/app/node_modules/clinic/bin.js:536
      if (err) throw err
               ^

Error: No files matching the pattern found
    at notFound (/app/node_modules/node-trace-log-join/index.js:65:15)
    at combine (/app/node_modules/node-trace-log-join/index.js:24:34)
    at /app/node_modules/node-trace-log-join/index.js:20:5
    at FSReqWrap.oncomplete (fs.js:135:15)
```
The issue is not related to my application as the application works fine it is only when using `clinic bubbleprof`.  Then `clinic doctor` works fine just not `bubbleprof`

## Steps to Reproduce (for bugs)

1. clinic bubbleprof -- node -r @std/esm ./app | bunyan

## Sample upload
Application crashes and none is generated

## Environment
* Clinic.js version:
```
/app # ./node_modules/.bin/clinic -v
v4.0.3
/app # ./node_modules/.bin/clinic doctor -v
v4.0.4
/app # ./node_modules/.bin/clinic bubbleprof -v
v2.1.3
```

* Node.js version:
```
/app # node -v
v8.14.0
/app # npm -v
6.4.1

```

* Browser name and version:

* Operating system and version:

**Comment by goto-bus-stop** [comment]
I can't reproduce this with a simple express app. Could you try to recreate the issue in a standalone app so i can have a closer look?

Also, I did find this: https://github.com/standard-things/esm/issues/84 it was fixed a long time ago, but may be relevant. Are you on a recent enough `@std/esm` version? (fwiw, it was renamed to `esm` a while ago, and @std/esm is no longer maintained)

**Comment by goto-bus-stop** [comment]
Ping :)

**Comment by OmgImAlexis** [comment]
I think I'm getting the same issue myself. I'm also using esm.

```
[  ==] Received Ctrl+C, closing process.../usr/lib/node_modules/clinic/bin.js:536
      if (err) throw err
               ^

Error: No files matching the pattern found
    at notFound (/usr/lib/node_modules/clinic/node_modules/node-trace-log-join/index.js:65:15)
    at combine (/usr/lib/node_modules/clinic/node_modules/node-trace-log-join/index.js:24:34)
    at /usr/lib/node_modules/clinic/node_modules/node-trace-log-join/index.js:20:5
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

**Comment by DylanC** [comment]
@OmgImAlexis - Do you have an example you can send us?
