### ISSUE TITLE
'Ctrl + C' not working for Mac, but works for Linux.

### ISSUE THREAD

**Issue by fr-nevin** [nearform/node-clinic#164]
## Expected Behavior
Bug: 'Ctrl+C' stops the doctor, and doesn't even reach to the analyzing part. 

## Current Behavior
I am trying to run clinic against a script, which needs to be run on background calling a polling function to check if there was an event triggered from the front end. Once the event has been sent from the front end, this polling function takes care of the event. Once it's done. I stop by using `Ctrl + C`, where the `Analyzing` bar doesn't appear.

## Environment
* Clinic.js version: "4.0.3",

* Node.js version: 10.15.3, npm - 6.4.1

* Browser name and version: Chrome Version 73.0.3683.103

* Operating system and version: Your OS is OS X 10.14.1 [Mac OS Mojave]

## Additional Info
The same command am using: 

`clinic doctor --on-port 'autocannon http://localhost:$PORT' -- node tasks/cathy.js` works for 2 of my friends Linux PC, but not on my MAC. (Going to confirm with another MAC friend soon. Will update it here.)

**Comment by mcollina** [comment]
Can you include a script that is triggering this behavior?

**Comment by fr-nevin** [comment]
@mcollina Hmm, it's a big script at the moment. 
I might need to make something small and run it. Let me give it a try and see if I can reproduce it.

**Comment by fr-nevin** [comment]
@mcollina I just put a simple code like this - 

> 
> const testFn = () => {
>   console.log('working..');
> }
> 
> setInterval(() => {
>   testFn();
> }, 1000);
>

**Comment by fr-nevin** [comment]
@mcollina I just put a simple code like this - 
`const initiateCathySync = () => {
      console.log('CATHY SYNC FUNCTION RUNNINGGGGGG!!!!')
}

setInterval(() => {
  initiateCathySync();
}, 1000);
`

**Comment by fr-nevin** [comment]
@mcollina But if there's a javascript file, which doesn't require stopping.. it would run it's course and shows the html metrics. 👍

**Comment by goto-bus-stop** [comment]
Does it only happen with the `--on-port` flag or also if you omit it?

**Comment by fr-nevin** [comment]
clinic doctor 'autocannon http://localhost:$PORT' -- node tools/cathySync.js - Ctrl + C not working.
clinic doctor '--autocannon http://localhost:$PORT' -- node tools/cathySync.js - Ctrl + C not working.
clinic doctor --autocannon -- node tools/cathySync.js - Ctrl + C not working.
clinic doctor --wrk -- node tools/cathySync.js - Ctrl + C not working.

All end up with the result: ^C[    ] Received Ctrl+C, closing process...
And ends the process.

I think problem lies with the handling of the `Ctrl+C` on MAC. Because, as I said earlier, without Ctrl + C, if it was a small script without
a continuous polling, it would show up with the results.

**Comment by fr-nevin** [comment]
@mcollina @goto-bus-stop Checked against 4 OS's in total (2 MAC and 2 Linux. )
Worked on both the linux, but not the MAC.

**Comment by DylanC** [comment]
@fr-nevin - Does this issue happen with v5 of Clinic?
`npm install -g clinic@5`

**Comment by DylanC** [comment]
This is working on Mac for me.

- Clinic.js version: "5.0.0",
- Node.js version: 12.16, npm - 6.13.4
- Browser name and version: Chrome Version 80.0.3987.122
- Operating system and version: Your OS is OS X 10.15.3

> dylanc@dc_mbp Clinic % clinic doctor --on-port 'autocannon http://localhost:$PORT' -- node node-clinic-doctor-examples/slow-io
> Running 10s test @ http://localhost:3000/
> 10 connections
> 
> Caught SIGINT, shutting down.
> [    ] Received Ctrl+C, closing process...Caught SIGINT, shutting down.

Let us know if you have any issues with current versions of Clinic.

**Comment by DylanC** [comment]
Dup of #152

**Comment by nath-abhishek** [comment]
Hi, I am still having this issue on Mac.

Clinic.js version: "6.0.3",
Node.js version: 12.16.1, npm - 6.13.4
Browser name and version: NA
Operating system and version: OS X 10.15.6

Thanks for awesome tool!

**Comment by MiloVahos** [comment]
Hi, I am having this issue on Windows

Clinic.js version: "7.0.1",
Node.js version: 14.15.3, npm - 6.14.9

**Comment by bijeshp** [comment]
Look for the SIGINT( catches ctrl+c event) event handlers in your code or the dependencies. 

if you have one,  `exit` the process in the handling. This worked for me(OsX `Catalina`/  clinic@9.0.0)
```
process.on('SIGINT', function() {
// do your handling 
// exit the process
    process.exit();
});
```

**Comment by Jakeii** [comment]
I'm having this issue only for `flame`. `doctor` and `bubbleprof` work just fine

**Comment by Jood80** [comment]
Same Issue on generating the reports upon clicking on "ctrl + c" on Linux:
- **Clinic.js**: "^13.0.0",
- **Node.js** :  ">=10.19.0",
- **"npm"**: "~3.10.0"
