### ISSUE TITLE
Error: ENOENT: no such file or directory, rename 'node_trace.1.log' -> '.clinic/31362.clinic-doctor/31362.clinic-doctor-traceevent'

### ISSUE THREAD

**Issue by atlas1119** [nearform/node-clinic#186]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Environment

* Clinic.js version:

* Node.js version:

* Browser name and version:

* Operating system and version:

**Comment by atlas1119** [comment]
node 9.4.0, Clinic  v4.1.0,  why？

**Comment by goto-bus-stop** [comment]
This usually means that something went wrong earlier in the process. could you show the full console output?

**Comment by DylanC** [comment]
@atlas1119 - Any update here? We would need more details to investigate.
