### ISSUE TITLE
Throw if npm start is passed in

### ISSUE THREAD

**Issue by mcollina** [nearform/node-clinic#194]
If we run `clinic doctor -- foo bar`, we should provide the user a proper error that guide them into using a Node.js executable.

**Comment by DylanC** [comment]
@mcollina - If we run "clinic doctor" without params we get a guide on how to use doctor in the terminal. Are you specifically talking about if a user ran "npm start" instead of "clinic doctor -- foo bar"?

**Comment by mcollina** [comment]
throwing if `clinic doctor -- npm start` is called.

**Comment by DylanC** [comment]
@mcollina - I understand the issue now. Running the command `clinic doctor -- npm start` will allow clinic to run and present the user with a blank graph.

**Comment by mcollina** [comment]
it should error instead.

Il giorno gio 30 gen 2020 alle ore 16:12 DylanC <notifications@github.com>
ha scritto:

**Comment by elrumordelaluz** [comment]
Is this solved?

I am trying to do
```
clinic doctor -- npm run start
```

and only gets

```
Clinic.js must be called with a `node` command line: `clinic doctor -- node script.js`
```

Node.js`v14.5.0`

**Comment by DylanC** [comment]
@elrumordelaluz - Clinic used to show a blank graph in this situation before if you passed an incorrect command such as:

**`clinic doctor -- npm run start`** (Incorrect)

Now you see the helpful error message instead which is telling you need to pass in a node argument for the command to work.
Clinic.js must be called with a `node` command line: 

**`clinic doctor -- node script.js`** (Correct)

So this aspect has been solved. :+1:

**Comment by elrumordelaluz** [comment]
Thank you @DylanC. So, probably there is the [`cli` section in the Documentation website](https://clinicjs.org/documentation/cli/#the-anatomy-of-a-command) that should be updated?

**Comment by DylanC** [comment]
@elrumordelaluz - Yes I would think so. Some of the wording is quite vague and does seem incorrect.

> Other ways we **might** run our application **could** be via an NPM script:

The page it links to looks more accurate:
https://clinicjs.org/documentation/cli/05-reference

The original [page](https://clinicjs.org/documentation/cli/#the-anatomy-of-a-command) you sent could do with updating.

**Comment by anmol5varma** [comment]
https://clinicjs.org/documentation/cli/
This page says that. we can use npm start as well.
Is it incorrect?

**Comment by SgtPooki** [comment]
https://clinicjs.org/documentation/cli/#the-anatomy-of-a-command

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/1173416/206788507-f68667e9-c12c-4901-b800-fa2704c171aa.png">

**Comment by ankitsny** [comment]
If someone wants to pass a npm script instead of `node script.js`
