### ISSUE TITLE
node: --trace-event-categories is not allowed in NODE_OPTIONS

### ISSUE THREAD

**Issue by pi0** [nearform/node-clinic#2]
Hey.

I've encountered this problem using node `9.2.0`, upgrading to `9.4.0` seems to resolve the problem. But what's your idea if adding a hard version dependency in `clinic`'s `package json` to prevent users confusing about this error or at least indicating it in REAME?

Thanks.

**Comment by mafintosh** [comment]
Yes you need 9.4.0 atm. a node core bug fix is being backported to node 8, which will make it run on latest 8 once that is released.

Do you want to send a PR adding a node requirement to package.json? :)

**Comment by pi0** [comment]
@mafintosh Thanks for your info. Yes, i can make PR if you agree. As you indicated this is being backported to 8.x, what's your idea if we catch this error at runtime and warn users about incompatible node version? (ie, a soft version requirement)

**Comment by mafintosh** [comment]
@pi0 I think it's hard to catch at runtime. Adding a "engine" field to the package.json is prob the way to go. Then once the fix is backported, we update the engine field to reflect that.

**Comment by hello2dj** [comment]
Whether this can be added to README?

**Comment by DanielRuf** [comment]
Still no notice in the readme.

**Comment by mcollina** [comment]
@mafintosh can you add the notice as well?

**Comment by mafintosh** [comment]
Added to the readme
