### ISSUE TITLE
Suggested additional reference for "potential Event Loop issue"

### ISSUE THREAD

**Issue by davisjam** [nearform/node-clinic#20]
I wrote [this guide](https://nodejs.org/en/docs/guides/dont-block-the-event-loop/) which might be helpful to include in the "Reference" section when "Doctor has found a potential Event Loop issue:".

**Comment by mcollina** [comment]
Would you like to send a PR? The text lives in https://github.com/nearform/node-clinic-doctor/blob/master/recommendations/event-loop-readmore.md.

**Comment by davisjam** [comment]
Will do. Thanks for pointing me to the right place.

**Comment by davisjam** [comment]
Closing, I opened an [issue for this](https://github.com/nearform/node-clinic-doctor/issues/117) in node-clinic-doctor.
