### ISSUE TITLE
bubbleprof is missing d3-color dependency

### ISSUE THREAD

**Issue by jsumners** [nearform/node-clinic#219]
![tmp 2020-03-06 14-53-38](https://user-images.githubusercontent.com/321201/76117695-47b7b900-5fba-11ea-8a7e-3208c0be329d.png)

**Comment by goto-bus-stop** [comment]
Fixed in bubbleprof@3.0.2. Thanks!

**Comment by jsumners** [comment]
Sorry for the duplicate. For some reason GitHub wasn't showing me the original and I couldn't tell if I reported it for flame or bubbleprof.

Thank you for resolving it.

**Comment by goto-bus-stop** [comment]
No worries! It was probably confusing because I transferred the issue to a different repo. Tbh, I would've forgotten about it if you hadn't opened another one :)

**Comment by jsumners** [comment]
That makes a lot more sense.
