### ISSUE TITLE
Uncaught SyntaxError: Missing initializer in const declaration

### ISSUE THREAD

**Issue by JosephAkayesi** [nearform/node-clinic#226]
## Expected Behavior
clinic bubble command should generate the bubble graph and render in browser successfully

## Current Behavior
clinic bubble file created successfully but cannot render. Page loads up initially and yu see loading but never loads up the actual graph.

Chrome console error says: 5488.clinic-bubbleprof.html:2068 Uncaught SyntaxError: Missing initializer in const declaration

Same error appears in mozilla firefox

## Steps to Reproduce (for bugs)

1. running clinic bubble --on-port 'autocannon -c2 -d5 localhost:5000' -- node dist/server
2.
3.
4.

## Environment

* Clinic.js version:

* Node.js version:

* Browser name and version:

* Operating system and version:

**Comment by goto-bus-stop** [comment]
Thanks for the report! Looks like this may be a minifier issue… With the `--debug` flag, I don't get the error:

```
clinic bubble --debug --autocannon [ -c2 -d5 / ] -- node server
```

**Comment by goto-bus-stop** [comment]
This is the underlying issue: https://github.com/terser/terser/issues/627

Published :package: `@clinic/bubbleprof v3.0.4` that uses an older version of terser. Thanks!

**Comment by dennisleehk01** [comment]
hi @goto-bus-stop, it seems the same bug happening for clinic doctor, mind to have a look on it also? thanks!

**Comment by remyma** [comment]
@dennisleehk01 same issue for me with clinic doctor. Using `--debug` as workaround as explained in previous comment fix this error.
