### ISSUE TITLE
clinic doctor -- node myserver.js do nothing

### ISSUE THREAD

**Issue by crystalfp** [nearform/node-clinic#232]
## Expected Behavior
Hope to run clinic doctor on my server: `clinic doctor -- node server/iie.js -c tests/config.yaml -s `

## Current Behavior
Clinic doctor outputs the help text and does not run my code.

Tried also to run the examples under [github](https://github.com/nearform/node-clinic-doctor-examples) without success..

## Steps to Reproduce (for bugs)
0. install globally `npm install -g clinic autocannon`
1. follow the instructions under `node-clinic-doctor-examples` to install and build the examples.
2. run the "slow event loop" example: `clinic doctor --autocannon [ / ] -- node slow-event-loop`
3. You will receive:
```
Clinic.js Doctor - v4.1.2

clinic doctor is the first step in profiling your application.
...
 --server URL               Use a different Clinic Upload ....
```
4. Nothing is run and nothing is saved on disk

## Sample upload
Nothing generated

## Environment

* Clinic.js version: 5.0.1
* Doctor version: 4.1.2

* Node.js version: 12.16.1
* npm version: 6.14.4

* Browser name and version: Chrome Version 81.0.4044.122 (Official Build) (64-bit)

* Operating system and version: Windows 10 64 bits

**Comment by crystalfp** [comment]
Partially works if I run it from a MINGW shell. Partially because the resulting html report is totally empty (and the traceevent file is missing), but maybe this is a different problem.

In the documentation I was not able to find platform requirements, so I deduce clinic works on Windows. If this is not the case, please add a section to the documentation and an error message in clinic.

It seems a so nice tool...
Anyway, thanks!
mario

**Comment by crystalfp** [comment]
... or point me to the platform requirements documentation, maybe I was not able to find it.
Thanks again!
mario

**Comment by DylanC** [comment]
@crystalfp - Does your application use web workers?

**Comment by crystalfp** [comment]
No

**Comment by goto-bus-stop** [comment]
Hmm I think `--` might mean something in cmd.exe, I'm not sure…

Do you see any command line output on the MinGW shell? There should at least be a table with statistics about Req/Sec and some other things if --autocannon is used.

**Comment by crystalfp** [comment]
Seems the problem is with PowerShell. If I run `cmd` inside the PowerShell and then launch clinic doctor it works. Let me check a little before closing the ticket.
It is not the first time that PowerShell has tricked me...

**Comment by crystalfp** [comment]
Quick test with doctor, flame and bubbleprof passed with success. So the culprit was PowerShell. Please add a note somewhere for my fellow Windows users to run clinic from cmd.com and not from PowerShell.
Thanks!
mario

**Comment by reply2future** [comment]
I faced the same issue,and there is no documents about the platform yet.

**Comment by tong3jie** [comment]
@reply2future me too

**Comment by akoval-caa** [comment]
me too
