### ISSUE TITLE
how can I change the logging(node_trace.*.log ) directory for doctor,bubble and flame 

### ISSUE THREAD

**Issue by ShivaPrabhakar** [nearform/node-clinic#256]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Environment

* Clinic.js version:

* Node.js version:

* Browser name and version:

* Operating system and version:

**Comment by jasnell** [comment]
Run `clinic doctor --help` for a list of command-line options. In this case, you'll want to use the `--dest` option to set the destination for collected data.
