### ISSUE TITLE
Error: No files matching the pattern found

### ISSUE THREAD

**Issue by womack** [nearform/node-clinic#28]
Whenever i run the command provided on npm 

`clinic doctor --on-port 'autocannon http://localhost:$PORT' -- node server.js`

I get the error below after autocannon has finished, not opening any html file; 

```
Error: No files matching the pattern found
    at notFound (C:\Users\Womac\AppData\Roaming\npm\node_modules\clinic\node_modules\node-trace-log-join\index.js:65:15)
    at combine (C:\Users\Womac\AppData\Roaming\npm\node_modules\clinic\node_modules\node-trace-log-join\index.js:24:34)
    at C:\Users\Womac\AppData\Roaming\npm\node_modules\clinic\node_modules\node-trace-log-join\index.js:20:5
    at FSReqWrap.oncomplete (fs.js:153:20)
```

Node version:  **v9.8.0**
Clinic version: **v0.8.1**

Clinic upload id: **b3bcbf4df8e380**

The repeatable test case is simply running the command detailed above, with the following server.js file

```
const restify = require('restify')
const {etagger, timestamp, fetchContent} = require('./util')()
const server = restify.createServer()

server.use(etagger().bind(server))

server.get('/seed/v1', function (req, res, next) {
    fetchContent(req.url, (err, content) => {
        if (err) 
            return next(err)
        res.send({data: content, url: req.url, ts: timestamp()})
        next()
    })
})

server.listen(3000);
```

**Comment by mcollina** [comment]
Clinic does not support Node 8.9, I'd recommend you to update to Node 8.11.

**Comment by womack** [comment]
Just to clarify, i should have mentioned this in the initial post; clinic **does** work, just not the "joined" command that runs autocannon at the same time, i can run the server with clinic doctor/flame, then run auto cannon, then stop the server and that works. But the joined command produces the above error.

**Comment by mcollina** [comment]
My bad, I read 8.9 instead of 9.8.

**Comment by mcollina** [comment]
cc @mafintosh

**Comment by qinkangwu** [comment]
update to Node 8.11.0

**Comment by mafintosh** [comment]
Should be fixed in the latest release
