### ISSUE TITLE
Event Loop issue References missing link for Load Shedding

### ISSUE THREAD

**Issue by binaryword** [nearform/node-clinic#34]
When using Doctor, the documentation for Event Loop issues mentions Load Shedding. While the phrase "Load Shedding" appears in the References section, there is no link for it with additional information.

<img width="898" alt="screen shot 2018-07-31 at 1 53 37 pm" src="https://user-images.githubusercontent.com/2080683/43477476-480c2e26-94c9-11e8-8144-d695cf2c774d.png">

**Comment by mcollina** [comment]
Thanks for reporting this!
In fact, this is a formatting error in our markdown files, check out https://github.com/nearform/node-clinic-doctor/pull/143.

**Comment by binaryword** [comment]
Aha, so the links were right in front of me the whole time! Thanks.

**Comment by mcollina** [comment]
No worries, good catch, we didn’t notice!
Il giorno mer 8 ago 2018 alle 04:34 binaryword <notifications@github.com>
ha scritto:
