### ISSUE TITLE
How to scroll up the flame chart?

### ISSUE THREAD

**Issue by gajus** [nearform/node-clinic#39]
Having a tall stack that goes outside the window, how do I scroll up?

<img width="1920" alt="screen shot 2018-08-08 at 12 50 27" src="https://user-images.githubusercontent.com/973543/43835382-a98c2598-9b09-11e8-9b89-e8860ac745c1.png">

**Comment by kamil-mech** [comment]
Thank you for flagging this. You have helped uncovering a bug - https://github.com/davidmarkclements/0x/pull/143
We are working on a fix and we will notify you once the issue gets resolved

**Comment by kamil-mech** [comment]
Issue has been resolved @gajus. Please update your clinic to get latest fixes. To avoid version-specific `npm` issues, I recommend a full reinstall:
```
npm un -g clinic
npm i -g clinic
```
