### ISSUE TITLE
clinic flame and clinic doctor not running on windows 7 and windows 10

### ISSUE THREAD

**Issue by tanmaypatil** [nearform/node-clinic#42]
## Expected Behavior
Hi all , 
I am trying to analyse the express application with mongodb backend . My set up is completely on windows laptop 7 .  With clinic doctor express server does not receive request and with clinic flame i get errors . With simple autocannon command i am able to call POST requests and records are getting created in database. 

My command line - for clinic flame and clinic doctor
option 1 - `clinic flame --on-port 'autocannon -method POST  localhost:3000/redeem' -- node server.js`
option 2 - `clinic flame --on-port 'autocannon -m POST  localhost:3000/redeem' -- node server.js`
clinic doctor --on-port 'autocannon -m POST  localhost:3000/redeem' -- node server.js

## Current Behavior
I get following output for _option1_ 

clinic flame helps you find synchronous bottlenecks
 by creating a flamegraph visualization that assists in identifying
  function calls that may be blocking the event loop.
  **clinic flame only supports Linux, OS X and Solaris.**

I get following error for second _option 2_
(node:6308) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): **Error: -m is not a recognized flag**
(node:6308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Steps to Reproduce (for bugs)
1. run the command as described in the paragraph above.

## Code for windows
My code is simple express application with mongodb as db . 

## Environment
* Clinic doctor version: 2.4.1 
 Clinic flame version : V4.0.11
 node version : 8.9.4
npm version : 5.6.0

```
server.js
const express = require('express');
const bodyparser = require('body-parser');
const MongoClient = require('mongodb').MongoClient;
const url = "mongodb://localhost:27017/";
const app = express();
let mongoDb = null;

app.use(bodyparser.json());
app.use(bodyparser.urlencoded({ extended: true }));
let options = { useNewUrlParser: true };
app.listen(3000, function () {
    MongoClient.connect(url, options, function (err, db) {
        if (err) {
            throw err;
        }
        else {
            console.log("db connected");
            mongoDb = db;
        }
    });
    console.log("app is ready on port 3000");
});

app.post('/redeem', (req, res) => {
    console.log("first line on post");
    let db = mongoDb.db("finacle");
    console.dir(req.body, { depth: null, colors: true });
    //db.collection('trans').insertOne( { 'couponCode' : 'A123', 'points' : 100});
    let message = '';
    try {
        if (req.body) {
            if (Array.isArray(req.body)) {
                for (let obj of req.body) {
                    console.log(obj);
                    db.collection('trans').insertOne(obj);
                }
                message = 'Total  ' + req.body.length + ' Objects saved';
            }
            else if(req.body.couponCode) {
                db.collection('trans').insertOne(req.body);
                console.log("saved inside a collection");
                message = 'Total  ' + req.body.length + ' saved';
            }
            else {
                console.log("100 coupons generation");
                let max = 100;
                let obj = {};
                let val = getRandomInt(max);
                let couponCode = 'B';
                for (let val= 0 ; val< max; val++) {
                    obj = Object.create(null);
                    couponCode = 'B' + val;
                    obj.couponCode = couponCode;
                    obj.points = getRandomInt(1000);
                    db.collection('trans').insertOne(obj);
                }
                message = 'Total objects created : '+ max;
            }
        }
        
    }
    catch (ex) {
        console.log("exception " + ex);
    }
    //let allRecs = db.collection('trans').find();
    let obj = { "message": message };
    res.status(200).json(obj);
    //mongoDb.close();
});

function getRandomInt(max) {
    return Math.floor(Math.random() * Math.floor(max));
}

```

**Comment by BridgeAR** [comment]
@mafintosh you have a Windows setup, right?

**Comment by mcollina** [comment]
Can you try with 8.11.3? There as been a few fixes in Node core that should
help.

We only have tested this on Windows 10, and not on Windows 7. I can confirm
it works smoothly on Windows 10.
Il giorno dom 12 ago 2018 alle 21:29 Ruben Bridgewater <
notifications@github.com> ha scritto:

**Comment by kamil-mech** [comment]
@tanmaypatil can you provide `autocannon -v` please?

**Comment by BridgeAR** [comment]
Ping @tanmaypatil

**Comment by rjoydip** [comment]
I am running win7 `clinic flame` and `clinic doctor` both are running fine. Note I am using simple `fastify` example.

**Comment by DylanC** [comment]
@tanmaypatil - This seems to be confirmed as working. Do let us know if you have this issue in the future.

**Comment by tong3jie** [comment]
windows 11 not support
