### ISSUE TITLE
Error opening a flame report

### ISSUE THREAD

**Issue by alexvictoor** [nearform/node-clinic#45]
## Expected Behavior
An HTML flame graph should be displayed

## Current Behavior
The HTML flame graph does not show up and a js error is thrown:
```
Uncaught TypeError: Cannot read property 'reduce' of undefined
    at 31038.clinic-flame.html:2752
    at time (31038.clinic-flame.html:2504)
    at HTMLUnknownElement.<anonymous> (31038.clinic-flame.html:2735)
    at Selection.selection_each [as each] (31038.clinic-flame.html:6684)
    at update (31038.clinic-flame.html:2730)
    at HTMLUnknownElement.<anonymous> (31038.clinic-flame.html:3053)
    at Selection.selection_each [as each] (31038.clinic-flame.html:6684)
    at chart (31038.clinic-flame.html:2973)
    at flameGraph (31038.clinic-flame.html:3158)
    at module.exports (31038.clinic-flame.html:442)
```
## Steps to Reproduce (for bugs)
1. clinic flame  -- node server.js 

## Sample upload

https://upload.clinicjs.org/public/ca684e50de8a7d39811df4d8906a4042ae67ce6f3eec27df92d1d4765b1294b8/31038.clinic-flame.html

## Environment
* Clinic version: 
v1.1.0
* Node version: 
v8.10.0
* Browser name and version: 
Chrome 68
* Operating system and version: 
OSX 10.12.6

**Comment by goto-bus-stop** [comment]
Hmm interesting, way down at the bottom of the source code is this:

```js
     visualizer({"merged":{"name":"all stacks","value":0,"top":0,"children":[]},"unmerged":{"name":"all stacks","value":0,"top":0,"children":[]}}, {})
```

so 0x didn't record any data. I'm not sure why that would be but I can fix the runtime error at least :P 
Does this happen for all source files or just some?

**Comment by mcollina** [comment]
@goto-bus-stop let's fix the runtime error. Ideally the best approach would be to give a nice error before the html file is generated.

**Comment by goto-bus-stop** [comment]
@mcollina https://github.com/davidmarkclements/d3-fg/pull/9/

**Comment by BridgeAR** [comment]
This has happened to me with Node master as well. I'll investigate a bit more about that in the next days.

**Comment by DylanC** [comment]
@mcollina @goto-bus-stop - Anything to do here or has the PR taken care of it?
