### ISSUE TITLE
Understanding and tracking memory issues

### ISSUE THREAD

**Issue by sravanthnag** [nearform/node-clinic#59]
Not a bug but an ask..
Clinic doctor is definitely easy to use and get a view of application performance.

My application is tagged as "Potential GC issue" by clinic doctor and the recommendations suggest to go through the node --inspect way to analyze the issue.

My code doesnot have a memory leak but a memory bloat i.e. its heavy at the startup itself and there is a lot of scavenge triggered by V8 and so a GC issue. 

Want to understand if Clinic is planning to provide any tool to profile and point out the source of issue from a memory point of view for e.g. like a heap dump analyzer would do for java application. 

I have been trying since sometime but am not able to get much details from the chrome heapdump analysis part as i don't get the source of the problem from it.

**Comment by mcollina** [comment]
In such cases I would recommend using BubbleProf. Most non-leak memory issues are caused by long asynchronous actions that make the GC do more work (the longer an object life is, the harder it would be to collect it).
