### ISSUE TITLE
Doctor has found an unknown issue - Node version 8.11.2

### ISSUE THREAD

**Issue by devcorpio** [nearform/node-clinic#60]
## Expected Behavior
To receive recommendations by Node Clinic.

## Current Behavior
Right now, node clinic show me the next message: "Doctor has found an unknown issue"

## Steps to Reproduce (for bugs)
1. build my app that use the framework next.js
2. NODE_ENV=production node_modules/.bin/clinic doctor -- node server/run.js
3. Navigate from different urls that proportionate my server
4. Control + C
5. Automatically, in my computer appears a node-clinic html page where appears differents graphics and also the message that says ""Doctor has found an unknown issue""

## Sample upload
https://upload.clinicjs.org/public/c0b96514f7ffb7577945884aca0fb2b0e54b52aa5154daf86f3a0d5bd29aa1f9/8970.clinic-doctor.html

## Environment

* Clinic version: 
Clinic v1.2.1
Doctor v3.4.0

* Node version: 
Node v8.11.2
Npm v6.4.0

* Browser name and version: 
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

* Operating system and version: 
Fedora 28; Linux x86_64

**Comment by mcollina** [comment]
Can you please upload the generated output from both flame and bubbleprof? That diagram looks interesting.

If you also can upload a cut-down version of the server, that would also be very interesting to check.

**Comment by devcorpio** [comment]
Hi @mcollina,

Yes, of course.

**flame**
https://upload.clinicjs.org/public/cbf93bae0e8e4578fb67252a118170cebe96bc8a898f963000b0cc136f3c04ea/12132.clinic-flame.html

**bubbleprof**:  https://upload.clinicjs.org/public/fc69591405bc62b108ab0133f50c4a5e0c0a04f72eee53c53366ac196e955675/11065.clinic-bubbleprof.html

Kind regards

**Comment by goto-bus-stop** [comment]
> If you also can upload a cut-down version of the server

@devcorpio It would be the source code (minus sensitive/private bits) that was used to generate this Doctor report. Ideally a smallish sample that reproduces the problem, but it might be tough to narrow down to that level!

**Comment by devcorpio** [comment]
Hi @goto-bus-stop,

Unfortunately, I'm not allowed to show the code :/ I'm sorry, I would like to send a copy, but I don't have the permission to send/show the code

**Comment by BridgeAR** [comment]
@devcorpio after looking into it, it turns out that there is not really enough data for clinic to make a good recommendation. Clicking on some links from time to time does not provide enough information for the algorithm to properly kick in. Please use a tool like [autocannon](https://github.com/mcollina/autocannon) to generate more load on your server.

Thanks a lot for reporting this though, since we should actually notify users about such situations when running clinic in the future.

**Comment by BridgeAR** [comment]
Hmm... that should definitely not happen. Can you please try two things: a) only run autocannon briefly and then end the application right away to see if there is to much data and we cut off the data at the wrong spot and b) is there any warning on your screen? Other people ran into the same issue when using the `cluster` module but that's not supported by clinic: https://github.com/nearform/node-clinic/issues/9

**Comment by devcorpio** [comment]
When I run node-clinic appears:

"cpu backend was already registered. Reusing existing backend
To generate the report press: Ctrl + C"

And the server starts to listen. Right now I'm executing autocannon without set many requests:

"node_modules/.bin/autocannon -c 1 -d 20 -M 5 http://localhost:3000/piso-barcelona"

Even executing that (or even less stressful requests) keeps appearing the error :(

After executing autocannon, If I go manually to an url of my webpage returns me a http status code 500, probably is related with my big issue with performance

P.D. I'm not using cluster module

**Comment by BridgeAR** [comment]
@devcorpio would you be so kind and upload the data? In that case we can take a closer look.

**Comment by mcollina** [comment]
Can you run:

```
clinic doctor --on-port 'node_modules/.bin/autocannon http://localhost:3000/piso-barcelona' -- node YOURSERVER.js
```

It seems you are running autocannon and quitting doctor after a significant amount of time.

**Comment by devcorpio** [comment]
Hi @mcollina,

Thanks a lot for your reply, using clinic as you said, show me another message! :) :)

First test:
----------------------------------

https://upload.clinicjs.org/public/4b02c6d04625e9d7840611f73bca8c6aa784fdf808421421c492edd3af1ff183/4750.clinic-doctor.html

"Detected a potential Garbage Collection issue"

Could this issue provoke a bottleneck in the web(very few requests/second), correct?

Second test: (another message!) ---> Detected a potential Event Loop issue  (server side rendering with react using renderToString, seems that could be the problem here, or atleast one of them...)

https://upload.clinicjs.org/public/13bf28239cac99da9ffcfcd748c073a72cdc39cd0694c576eaef25d3aa4af54b/5461.clinic-doctor.html  

https://upload.clinicjs.org/public/9122d644e511187735ac6f4e2ecac93e3fd7c763e3f42799d3a3f4f507090757/6148.clinic-bubbleprof.html


I can't generate flame, throws me an error (.txt attached)

Thanks all of your for your kindness and the time you are investing for help me, I appreciate it
[flame_generation_error.txt](https://github.com/nearform/node-clinic/files/2421319/flame_generation_error.txt)

**Comment by devcorpio** [comment]
Hi @mcollina, @goto-bus-stop, @BridgeAR,

Finally I have found the core problem of performance.

The problem is directly related with the library immutablejs(**fromJS** method), the process of transform the data received for an api(a really huge structures of data) is really overkill.

I have an universal web app, in the server side rendering the inadequate use of the library is really painful. (in the cliend side too, but "less" important for me, in this moment.)

Thank you all for your help

Kind regards and have a nice week :)

**Comment by jasnell** [comment]
@devcorpio .. thank you for being patient with clinic as you were stepping through this. I definitely hope it has been useful for you. 

@mcollina ... Given the sensitivity of clinic to either having too much or too little data to use, I'm wondering if there are some warnings we could apply here to users to improve the experience. It may be a bit difficult to come up with the right heuristic to display the warning, however. What do you think?

**Comment by devcorpio** [comment]
@mcollina I am sorry for the delay for the response. 

Yes, definitely!, thanks to the clinic flame I could see the main pains of the application(in this case an inadequate use of immutablejs).

@jasnell  :+1: :)

**Comment by dhairya0904** [comment]
clinic doctor has suddenly stopped working for me, seems to be a similar issue.

```
SyntaxError: Unexpected token , in JSON at position 1408
    at JSON.parse (<anonymous>)
    at Parser._transform (/opt/homebrew/lib/node_modules/clinic/node_modules/@nearform/trace-events-parser/index.js:41:34)
    at Parser.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Parser.Writable.write (node:internal/streams/writable:334:10)
    at ReadStream.ondata (node:internal/streams/readable:751:22)
    at ReadStream.emit (node:events:365:28)
    at ReadStream.Readable.read (node:internal/streams/readable:525:10)
    at flow (node:internal/streams/readable:1009:34)
```
