### ISSUE TITLE
--dest option is only available with clinic doctor

### ISSUE THREAD

**Issue by pamls** [nearform/node-clinic#64]
## Expected Behavior
`--dest` is a great and useful option. Unfortunaly this option is only available for _Doctor_

## Current Behavior
`--dest` option is ignored for _Flame_ and _Bubbleprof_

* `clinic doctor --dest tmp/ -- node start.js` => output files are in the tmp folder
* `clinic flame--dest tmp/ -- node start.js` => output files are **NOT** in the tmp folder
* `clinic bubbleprof --dest tmp/ -- node start.js` => output files are **NOT** in the tmp folder

## Environment
* Clinic version: 1.3.0
* Node version: 8.11.1
* Operating system and version: Windows 10 64-bit 

Thank you! Very nice tool!

**Comment by mcollina** [comment]
Thanks for reporting! We are definitely adding it to all the other tool, all that work is already planned!

**Comment by DylanC** [comment]
@pamls - Try the latest version. This feature has been added to the other tools.
