### ISSUE TITLE
Flame graph not works on linux

### ISSUE THREAD

**Issue by gtzinos** [nearform/node-clinic#65]
- Execute: clinic flame --on-port=’autocannon -c2 localhost:$PORT/seed/v1’ -- node index.js
- After 2 minutes i press CTRL + C
- Console export: -
- Export: isolate file.log

where is the html file ?

Node: 8.9
OS: ubuntu 16.04

Index.js

`    'use strict'

    const restify = require('restify')
    const { etagger, timestamp, fetchContent } = require('./util')()
    const server = restify.createServer()

    server.use(etagger().bind(server))

    server.get('/seed/v1', function (req, res, next) {
      fetchContent(req.url, (err, content) => {
        if (err) return next(err)
        res.send({data: content, url: req.url, ts: timestamp()})
        next()
      })
    })

    server.listen(3000)`

util.js
`
  "use strict";

  require("events").defaultMaxListeners = Infinity;
  const crypto = require("crypto");

  module.exports = () => {
    const content = crypto.rng(5000).toString("hex");
    const ONE_MINUTE = 60000;
    var last = Date.now();

    function timestamp() {
      var now = Date.now();
      if (now - last >= ONE_MINUTE) last = now;
      return last;
    }

    function etagger() {
      var cache = {};
      var afterEventAttached = false;
      function attachAfterEvent(server) {
        if (attachAfterEvent === true) return;
        afterEventAttached = true;
        server.on("after", (req, res) => {
          if (res.statusCode !== 200) return;
          if (!res._body) return;
          const key = crypto
            .createHash("sha512")
            .update(req.url)
            .digest()
            .toString("hex");
          const etag = crypto
            .createHash("sha512")
            .update(JSON.stringify(res._body))
            .digest()
            .toString("hex");
          if (cache[key] !== etag) cache[key] = etag;
        });
      }
      return function(req, res, next) {
        attachAfterEvent(this);
        const key = crypto
          .createHash("sha512")
          .update(req.url)
          .digest()
          .toString("hex");
        if (key in cache) res.set("Etag", cache[key]);
        res.set("Cache-Control", "public, max-age=120");
        next();
      };
    }

    function fetchContent(url, cb) {
      setImmediate(() => {
        if (url !== "/seed/v1")
          cb(Object.assign(Error("Not Found"), { statusCode: 404 }));
        else cb(null, content);
      });
    }

    return { timestamp, etagger, fetchContent };
  };

`

**Comment by mcollina** [comment]
Can you please try with Node 8.12.0? Can you upload a sample script file to reproduce?

**Comment by gtzinos** [comment]
I used 8.12 but now i have an error:

/bin/sh: 1: ’autocannon: not found
Fatal error in process observed by 0x. Incomplete V8 isolate log deleted. To preserve these logs, enable debugging (e.g. `DEBUG=0x* 0x my-app.js`)

But i can execute autocannon commands

**Comment by gtzinos** [comment]
I did before

**Comment by gtzinos** [comment]
![screenshot from 2018-10-11 21-05-42](https://user-images.githubusercontent.com/11459192/46824429-761b6f80-cd99-11e8-8f5f-59ebb68240ee.png)

**Comment by gtzinos** [comment]
autocannon -c100 localhost:3000/seed/v1

![screenshot from 2018-10-11 21-08-50](https://user-images.githubusercontent.com/11459192/46824561-e924e600-cd99-11e8-84ae-a44cdfa0a051.png)

**Comment by BridgeAR** [comment]
Runs fine on 10 and throws an error on 8.12.0 for me:

```
bufferAnalysing data
/home/ruben/.nvm/versions/node/v8.12.0/lib/node_modules/clinic/bin.js:261
        if (err) throw err
                 ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:384:11)
    at spawnSync (child_process.js:520:38)
    at ticksToTree (/home/ruben/.nvm/versions/node/v8.12.0/lib/node_modules/clinic/node_modules/0x/lib/ticks-to-tree.js:30:21)
    at render (/home/ruben/.nvm/versions/node/v8.12.0/lib/node_modules/clinic/node_modules/0x/lib/render.js:19:17)
    at generateFlamegraph (/home/ruben/.nvm/versions/node/v8.12.0/lib/node_modules/clinic/node_modules/0x/index.js:76:22)
    at visualize (/home/ruben/.nvm/versions/node/v8.12.0/lib/node_modules/clinic/node_modules/0x/index.js:119:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

I'll have a closer look at 8 and why we run into an issue there.

**Comment by DylanC** [comment]
@gtzinos - Support for Node v8 has been dropped. Please try Node Clinic in Node v10.x or greater.

**Comment by Rishabh570** [comment]
> I used 8.12 but now i have an error:
> 
> /bin/sh: 1: ’autocannon: not found
> Fatal error in process observed by 0x. Incomplete V8 isolate log deleted. To preserve these logs, enable debugging (e.g. `DEBUG=0x* 0x my-app.js`)
> 
> But i can execute autocannon commands

I also got this exact error but this was just because of the quote being messed up during copy-paste.
