### ISSUE TITLE
out of memory exception while running bubbleprof on 10s autocannon

### ISSUE THREAD

**Issue by ZauberNerd** [nearform/node-clinic#72]
## Expected Behavior

After finishing the HTTP benchmarks and pressing `CTRL-C` on the clinic bubbleprof process it should finish analyzing data and show results in a new browser window.

## Current Behavior

After finishing the HTTP benchmarks and pressing `CRTL-C` the clinic process dies with an out-of-memory exception.

## Steps to Reproduce (for bugs)

1. `npx create-hops-app@next --hops-version next --template hops-template-react@next my-app`
2. `cd my-ap`
3. `./node_modules/.bin/hops build -p`
4. `clinic bubbleprof -- node ./node_modules/.bin/hops serve -p`
5. `autocannon http://localhost:8080`
6. press `CTRL-C` on the clinic process after autocannon finishes and observe an out-of-memory exception.

## Sample upload

https://upload.clinicjs.org/public/54836c48aa37cb3dd80c003d6c9667e27c1fcd9f3639531c5e87294fe4021f62/12016.clinic-bubbleprof.html

<details>
<summary>example stack trace output</summary>
<pre>
 /tmp/my-app $ clinic bubbleprof -- node ./node_modules/.bin/hops serve -p
To generate the report press: Ctrl + C
[my-app] started in production mode
Server listening at http://localhost:8080
^CAnalysing data

<--- Last few GCs --->

[12008:0x36fd870]    52854 ms: Mark-sweep 1394.6 (1424.0) -> 1393.9 (1423.0) MB, 959.0 / 0.0 ms  (average mu = 0.054, current mu = 0.019) allocation failure scavenge might not succeed
[12008:0x36fd870]    52862 ms: Scavenge 1394.7 (1423.0) -> 1394.0 (1423.5) MB, 5.7 / 0.0 ms  (average mu = 0.054, current mu = 0.019) allocation failure 
[12008:0x36fd870]    52871 ms: Scavenge 1394.9 (1423.5) -> 1394.2 (1424.0) MB, 6.1 / 0.0 ms  (average mu = 0.054, current mu = 0.019) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x326ace1dbe1d]
    1: StubFrame [pc: 0x326ace1b4fbf]
Security context: 0x0d3813d9e6e1 <JSObject>
    2: /* anonymous */ [0x103d0e502ae9] [/home/zaubernerd/.nvm/versions/node/v10.13.0/lib/node_modules/clinic/node_modules/terser/dist/bundle.js:~44] [pc=0x326ace6ebb89](this=0x103d0e502461 <qn map = 0x22e3c483dcf1>,i=0x05c001e94d21 <AST_Number map = 0x22e3c4822b79>,r=0x16382e83f751 <JSFunction u (sfi = 0x10fb5920a109)>)...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8daaa0 node::Abort() [node]
 2: 0x8daaec  [node]
 3: 0xad73ce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xad7604 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xec4c32  [node]
 6: 0xec4d38 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xed0e12 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xed1744 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xed43b1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xe9d834 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x113cf9e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x326ace1dbe1d 
Aborted (core dumped)
</pre>
</details>

## Environment

* Clinic version: v2.0.0 Doctor v3.5.0

* Node version: v10.13.0 npm v6.4.1

* Browser name and version: Chrome 70

* Operating system and version: Linux 64-bit

**Comment by jasnell** [comment]
This occurs generally because bubbleprof requires a rather large amount of diagnostic data to be generated by Node.js and loaded into the analysis engine. Depending on the amount of async activity being performed by the application, there are possibly two approaches to resolving this:

1. You can try a shorter benchmark (e.g. 5 seconds instead of 10). This will reduce the amount of profile data necessary for bubbleprof to sift through but it can also limit the fidelity of the profiling, so it is definitely a trade off.

2. Try using the v8 memory flags (e.g. `NODE_OPTIONS="--max-old-space-size=N" clinic bubble ...`, etc) to adjust the amount of memory available usable by the Node.js instance.

If either of these do not work, please let us know! :-)
