### ISSUE TITLE
do not work if process exit with non-zero code

### ISSUE THREAD

**Issue by NassiHarel** [nearform/node-clinic#73]
## Steps to Reproduce (for bugs)

1. npm install -g clinic
2. clinic doctor -- node app.js
3. To generate the report press: Ctrl + C
4. working....
5. after hit Ctrl + C

 SIGINT
 exit code 1

/home/user/.nvm/versions/node/v10.7.0/lib/node_modules/clinic/bin.js:323
      if (err) throw err
               ^

Error: process exited with exit code 1
    at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v10.7.0/lib/node_modules/clinic/node_modules/@nearform/doctor/index.js:102:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)

## Environment

* Clinic version: 

* Node version: v10.7.0
* Npm version: v6.1.0

* Browser name and version: 

* Operating system and version:

**Comment by mcollina** [comment]
Can you update to latest node.js v10 (v10.13.0)?

**Comment by NassiHarel** [comment]
Still the same problem

/home/user/.nvm/versions/node/v10.13.0/lib/node_modules/clinic/bin.js:323
      if (err) throw err
               ^

Error: process exited with exit code 1
    at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v10.13.0/lib/node_modules/clinic/node_modules/@nearform/doctor/index.js:102:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

**Comment by NassiHarel** [comment]
Problem found:
I have these lines in my code....

process.on('SIGTERM', () => {
        log.info('SIGTERM', { component });
        process.exit(1);
});

**Comment by NassiHarel** [comment]
I think It's not related to SIGTERM event listener.
It's because of process.exit(1);
it works after I changed it to process.exit(0);

```
        process.on('exit', (code) => {
            log.info(`exit code ${code}`);
        });
        process.on('SIGINT', () => {
            log.info('SIGINT');
            process.exit(0);
        });
        process.on('SIGTERM', () => {
            log.info('SIGTERM');
            process.exit(0);
        });
         process.on('unhandledRejection', (error) => {
            log.error(`unhandledRejection: ${error.message}`);
            process.exit(1);
        });
        process.on('uncaughtException', (error) => {
            log.error(`uncaughtException: ${error.message}`);
            process.exit(1);
        });
```

**Comment by ovhemert** [comment]
Same problem for me. Still need my trace output, even with intentional `process.exit(1)`.

Should be fixed in the individual packages doctor / flame / bubbleprof, because they throw the error to Clinic before the trace event file is moved to the logging directory.

I will create issues in the individual package repos and send PR's to fix this.

Starting with doctor: nearform/node-clinic-doctor#189.

**Comment by ovhemert** [comment]
@NassiHarel : I noticed that the changes I've made are merge into the v2.1.0 release.

Does this close the issue for you?
