### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by MattMorgis** [nearform/node-clinic#89]
## Expected Behavior

`npm install -g clinic` should install clinic

## Current Behavior

`npm install -g clinic`
```
npm ERR! code E401
npm ERR! 401 Unauthorized: @nearform/flame@^3.4.1
```

`npm install -g clinic@2.0.0`

```
npm ERR! code E401
npm ERR! 401 Unauthorized: @nearform/flame@^3.0.0
```
## Steps to Reproduce (for bugs)

1. `npm install -g clinic`
2. or `npm install -g clinic@2.0.0`

It appears [clinic references flame v3.4.1](https://github.com/nearform/node-clinic/blob/master/package.json#L23), but the [most recent version published to npm](https://www.npmjs.com/package/@nearform/clinic-flame) is 2.0.0.

## Environment

* Clinic version: 

* Node version: Node `v10.14.0` npm `v6.4.1`

* Browser name and version: 

* Operating system and version: 
`OSX 10.12.6`

**Comment by MattMorgis** [comment]
This might be an issue on my end.

I rolled back to Node.js version 8 and now I get 

```
npm ERR! code E401
npm ERR! 404 401 Unauthorized: @nearform/trace-events-parser@^1.0.4
```

and @nearform/trace-events-parser@^1.0.4 **is** published on npm

**Comment by goto-bus-stop** [comment]
https://www.npmjs.com/package/@nearform/flame is the real package at v3.x, @nearform/clinic-flame is a historical artifact I think. Not sure what could be causing this though!

**Comment by MattMorgis** [comment]
Worked for me on a different machine just fine so I think something is wrong with my environment
